name: Deploy to Cloud Run

on:
  push:
    branches: [ master ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for gcr
        run: gcloud auth configure-docker --quiet

      - name: Build container image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/watchtogether-backend:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/watchtogether-backend:${{ github.sha }}
          gcloud run deploy watchtogether-backend \
            --image $IMAGE \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars JWT_SECRET=${{ secrets.JWT_SECRET }},CLIENT_API_KEY=${{ secrets.CLIENT_API_KEY }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},VERTEX_MODEL=${{ secrets.VERTEX_MODEL }}
