name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build and Push Container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/watchtogether:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/watchtogether:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: watchtogether
          region: ${{ secrets.GCP_REGION }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/watchtogether:${{ github.sha }}
          env_vars: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CLIENT_API_KEY=${{ secrets.CLIENT_API_KEY }}
            VERTEX_MODEL=${{ secrets.VERTEX_MODEL }}
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
