name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build and push container
        run: |-
          docker build -t "us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/watchtogether-backend/app:${{ github.sha }}" .
          docker push "us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/watchtogether-backend/app:${{ github.sha }}"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: watchtogether-backend
          region: ${{ secrets.GCP_REGION }}
          image: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/watchtogether-backend/app:${{ github.sha }}
          env_vars: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CLIENT_API_KEY=${{ secrets.CLIENT_API_KEY }}
            VERTEX_MODEL=${{ secrets.VERTEX_MODEL }}
            GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
